#!/bin/bash

if [ "$NOLINT" == "1" ] || [ "$NOLINT" == true ]; then exit 0; fi

if [ "$TRAVIS" != true ] && [ -z ${NOLINT+x} ]; then
    read -p "Do you want to run lints? (y/N): " yn </dev/tty
    case $yn in
        [Yy]* ) true;;
        * ) exit 0;;
    esac
fi

set -v

FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
status2=$?

TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` $(dirname $0)/test_pylint
pylint_status=$?
exit $((${status1} || ${status2} || ${pylint_status}))
