#!/bin/bash
set -ex
if [ "$DOCKER_TAG" == latest ]; then
    source hooks/_common
    # Push all tags, that should be built already
    for repo in $REPOS; do
        for version in $VERSIONS; do
            docker image push "$DOCKER_REPO:$(flavor $repo $version)"
        done
    done
fi
