#!/bin/bash
set -ex
if [ "$DOCKER_TAG" == latest ]; then
    # Push other tags, that should have been built already
    source hooks/variables
    for repo in $OTHER_REPOS; do
        repo="$(basename $repo)"
        for version in $OTHER_VERSIONS; do
            docker image push "$DOCKER_REPO:$repo-$version"
        done
    done
fi
