#!/bin/bash
set -ex
if [ "$DOCKER_TAG" == latest ]; then
    # Build other tags, using cache to get it faster
    source hooks/variables
    repo="$(basename $DEFAULT_REPO)"
    version="$DEFAULT_VERSION"
    docker image tag "$IMAGE_NAME" "$DOCKER_REPO:$repo-$version"
    for repo in $OTHER_REPOS; do
        repo="$(basename $repo)"
        for version in $OTHER_VERSIONS; do
            docker image build \
                --build-arg ODOO_REPO="$repo" \
                --build-arg VERSION="$version" \
                --tag "$DOCKER_REPO:$repo-$version"
        done
    done
fi
