#!/bin/bash
set -ex
if [ "$DOCKER_TAG" == latest ]; then
    source hooks/_common
    # Build all tags, using cache to get it faster
    for repo in $REPOS; do
        for version in $VERSIONS; do
            docker image build \
                --build-arg ODOO_REPO="$repo" \
                --build-arg VERSION="$version" \
                --tag "$DOCKER_REPO:$(flavor $repo $version)" \
                .
        done
    done
fi
