#!/usr/bin/env python

import sys
import os
module_path = sys.argv[1]

if module_path.endswith('_unported'):
    sys.exit(1)
for name in ['__openerp__.py', '__odoo__.py', '__terp__.py']:
    file_name = os.path.join(module_path, name)
    if os.path.isfile(file_name):
        with open(file_name) as fobj:
            metadata = eval(fobj.read())
        if metadata['installable']:
            sys.exit(0)
        else:
            sys.exit(1)
print "unable to find addon metadata for %s" % module_path
sys.exit(2)
