#!/usr/bin/python
"""Usage: clone_oca_dependencies [<checkout_dir> <build_dir>]

Arguments:

checkout_dir: the directory in which the dependency repositories will be cloned
build_dir: the directory in which the tested repositories have been cloned

If no arguments are provided, default to the layout used in the OCA travis
configuration.

The program will process the file oca_dependencies.txt at the root of the
tested repository, and clone the dependency repositories in checkout_dir,
before recursively processing the oca_dependencies.txt files of the
dependencies.

The expected format for oca_dependencies.txt:

* comment lines start with # and are ignored
* a dependency line contains:
  - the name of the OCA project
  - (optional) the URL to the git repository (defaulting to the OCA repository)
  - (optional) the name of the branch to use (defaulting to ${VERSION})
"""
from __future__ import print_function
import sys
import os
import os.path as osp
import subprocess
import logging


_logger = logging.getLogger()

travis_repo_slug = os.environ.get(
    "TRAVIS_REPO_SLUG",
    "OCA/maintainer-quality-tools",
)
travis_repo_owner = travis_repo_slug.split("/")[0]


def parse_depfile(depfile):
    deps = []
    for line in depfile:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split()
        repo = parts[0]
        if len(parts) > 2:
            branch = parts[2]
        else:
            branch = os.environ.get('VERSION', '8.0')
        if len(parts) > 1:
            url = parts[1]
        else:
            url = 'https://github.com/%s/%s' % (travis_repo_owner, repo)
        deps.append((repo, url, branch))
    return deps


def git_checkout(home, reponame, url, branch):
    checkout_dir = osp.join(home, reponame)
    if not osp.isdir(checkout_dir):
        command = ['git', 'clone', '-q', url, '-b', branch, checkout_dir]
    else:
        command = ['git', '--git-dir=' + os.path.join(checkout_dir, '.git'),
                   '--work-tree=' + checkout_dir, 'pull', url, branch]
    _logger.info('Calling %s', ' '.join(command))
    subprocess.check_call(command)
    return checkout_dir


def run(home, build_dir):
    dependencies = []
    processed = set()
    reqfilenames = []
    if osp.isfile(osp.join(build_dir, 'requirements.txt')):
        reqfilenames.append(osp.join(build_dir, 'requirements.txt'))
    for repo in os.listdir(build_dir):
        _logger.info('examining %s', repo)
        processed.add(repo)
        depfilename = osp.join(build_dir, repo, 'oca_dependencies.txt')
        dependencies.append(depfilename)
        reqfilename = osp.join(build_dir, repo, 'requirements.txt')
        if osp.isfile(reqfilename):
            reqfilenames.append(reqfilename)
    for depfilename in dependencies:
        try:
            with open(depfilename) as depfile:
                deps = parse_depfile(depfile)
        except IOError:
            deps = []
        for depname, url, branch in deps:
            _logger.info('* processing %s',  depname)
            if depname in processed:
                continue
            processed.add(depname)
            checkout_dir = git_checkout(home, depname, url, branch)
            new_dep_filename = osp.join(checkout_dir, 'oca_dependencies.txt')
            reqfilename = osp.join(checkout_dir, 'requirements.txt')
            if osp.isfile(reqfilename):
                reqfilenames.append(reqfilename)
            if new_dep_filename not in dependencies:
                dependencies.append(new_dep_filename)
    for reqfilename in reqfilenames:
        command = ['pip', 'install', '--no-binary', 'pycparser',
                   '-Ur', reqfilename]
        _logger.info('Calling %s', ' '.join(command))
        subprocess.check_call(command)


if __name__ == '__main__':
    if len(sys.argv) == 1:
        home = os.environ['HOME']
        build_dir = osp.join(home, 'build', travis_repo_owner)
    elif len(sys.argv) == 2 or len(sys.argv) > 3:
        print(__doc__)
        sys.exit(1)
    else:
        home = sys.argv[1]
        build_dir = sys.argv[2]
    run(home, build_dir)
