#!/usr/bin/env python
# coding: utf-8

from test_server import main as test_server_main
import time
import subprocess
import threading
import os


class TestServerThread(threading.Thread):
    def run(self):
        test_server_main()

def main(argv=None):
    """Run integration tests with RSpec"""
    thread = TestServerThread()
    thread.daemon = True
    thread.start()

    time.sleep(20)
    print("server started, starting RSpec test")
    test_result = subprocess.call(["bundle", "exec", "rspec"])
    if test_result == 0:
        print("""
       __.-._
       '-._"7'
        /'.-c
        |  /T
       _)_/LI
Zero failures, you have.
    All good, it is""")

    return test_result

if __name__ == '__main__':
    exit(main())
