#!/bin/bash

export SHIPPABLE_CMD_DI_10_BZR_INSTALL="sudo apt-get update && sudo apt-get install -yf bzr"
export SHIPPABLE_CMD_CI_20_FIX_POSTGRES_SSL="sudo mkdir -p /etc/ssl/private-copy; sudo mkdir -p /etc/ssl/private; sudo mv /etc/ssl/private/* /etc/ssl/private-copy/; sudo rm -r /etc/ssl/private; sudo mv /etc/ssl/private-copy /etc/ssl/private; sudo chmod -R 0700 /etc/ssl/private; sudo chown -R postgres /etc/ssl/private"
export SHIPPABLE_CMD_CI_30_PSQL_START='sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c "config_file=/etc/postgresql/9.3/main/postgresql.conf" > /tmp/pg.log 2>&1 & sleep 5s"'
export SHIPPABLE_CMD_CI_40_FIX_ROOT_ODOO="find ${HOME} -name server.py -exec sed -i \"s/== 'root'/== 'force_root'/g\" {} \;"
export FNAME_SCRIPT_SH="$(dirname ${BASH_SOURCE[0]})/script_shippable_install_nigthly.sh"
export CMD_STRS_STARTS="SHIPPABLE_CMD_DI_"
$(dirname ${BASH_SOURCE[0]})/run_env_cmd ${FNAME_SCRIPT_SH} && ${FNAME_SCRIPT_SH}
export CMD_STRS_STARTS="SHIPPABLE_CMD_CI_"
$(dirname ${BASH_SOURCE[0]})/run_env_cmd ${FNAME_SCRIPT_SH} && ${FNAME_SCRIPT_SH}
