#!/bin/bash

export SHIPPABLE_CMD_DI_10_BZR_INSTALL="sudo apt-get update && sudo apt-get install -yf bzr"
export FNAME_SCRIPT_SH="$(dirname ${BASH_SOURCE[0]})/script_shippable_install_nigthly.sh"
export CMD_STRS_STARTS="SHIPPABLE_CMD_DI_"
$(dirname ${BASH_SOURCE[0]})/run_env_cmd ${FNAME_SCRIPT_SH} && ${FNAME_SCRIPT_SH}
