#!/bin/bash

FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
status2=$?

if [[ "${status1}${status2}" == "00" ]]; then
  echo "Flake8 OK"
  exit 0
else
  echo "Flake8 ERRORS"
  exit 1
fi
