#!/usr/bin/env python

from __future__ import print_function

import re
import os
import subprocess
import sys
from getaddons import get_addons
from getaddons import get_modules
from travis_helpers import success_msg, fail_msg


def has_test_errors(fname, dbname, odoo_version, check_loaded=True):
    """
    Check a list of log lines for test errors.
    Extension point to detect false positives.
    """
    # Rules defining checks to perform
    # this can be
    # - a string which will be checked in a simple substring match
    # - a regex object that will be matched against the whole message
    # - a callable that receives a dictionary of the form
    #     {
    #         'loglevel': ...,
    #         'message': ....,
    #     }
    ERRORS_IGNORE = [
        'Mail delivery failed',
        'failed sending mail',
        ]
    ERRORS_REPORT = [
        lambda x: x['loglevel'] == 'CRITICAL',
        'At least one test failed',
        'no access rules, consider adding one',
        ]
    # Only check ERROR lines before 7.0
    if odoo_version < '7.0':
        ERRORS_REPORT.append(
            lambda x: x['loglevel'] == 'ERROR')

    def make_pattern_list_callable(pattern_list):
        for i in range(len(pattern_list)):
            if isinstance(pattern_list[i], basestring):
                regex = re.compile(pattern_list[i])
                pattern_list[i] = lambda x: regex.match(x['message'])
            elif hasattr(pattern_list[i], 'match'):
                regex = pattern_list[i]
                pattern_list[i] = lambda x: regex.match(x['message'])

    make_pattern_list_callable(ERRORS_IGNORE)
    make_pattern_list_callable(ERRORS_REPORT)

    print("-"*10)
    # Read log file removing ASCII color escapes:
    # http://serverfault.com/questions/71285
    color_regex = re.compile(r'\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]')
    log_start_regex = re.compile(
        r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3} \d+ (?P<loglevel>\w+) '
        '(?P<db>(%s)|([?])) (?P<logger>\S+): (?P<message>.*)$' % dbname)
    log_records = []
    last_log_record = dict.fromkeys(log_start_regex.groupindex.keys())
    with open(fname) as log:
        for line in log:
            line = color_regex.sub('', line)
            match = log_start_regex.match(line)
            if match:
                last_log_record = match.groupdict()
                log_records.append(last_log_record)
            else:
                last_log_record['message'] = '%s\n%s' % (
                    last_log_record['message'], line.rstrip('\n')
                )
    errors = []
    for log_record in log_records:
        ignore = False
        for ignore_pattern in ERRORS_IGNORE:
            if ignore_pattern(log_record):
                ignore = True
                break
        if ignore:
            break
        for report_pattern in ERRORS_REPORT:
            if report_pattern(log_record):
                errors.append(log_record['message'])
                break

    if check_loaded:
        if not [r for r in log_records if 'Modules loaded.' == r['message']]:
            errors.append({'message': "Modules loaded message not found."})

    if errors:
        for e in errors:
            print(e['message'])
        print("-"*10)
    return len(errors)


def parse_list(comma_sep_list):
    return [x.strip() for x in comma_sep_list.split(',')]


def main():
    travis_home = os.environ.get("HOME", "~/")
    travis_build_dir = os.environ.get("TRAVIS_BUILD_DIR", "../..")
    odoo_unittest = os.environ.get("UNIT_TEST")
    odoo_exclude = os.environ.get("EXCLUDE")
    odoo_include = os.environ.get("INCLUDE")
    odoo_version = os.environ.get("VERSION")
    options = os.environ.get("OPTIONS", "").split()
    install_options = os.environ.get("INSTALL_OPTIONS", "").split()
    if not odoo_version:
        # For backward compatibility, take version from parameter
        # if it's not globally set
        odoo_version = sys.argv[1]
        print("WARNING: no env variable set for VERSION. "
              "Using '%s'" % odoo_version)

    if odoo_version == "6.1":
        install_options += ["--test-disable"]
        test_loglevel = 'test'
    else:
        options += ["--test-enable"]
        if odoo_version == '7.0':
            test_loglevel = 'test'
        else:
            test_loglevel = 'info'

    odoo_full = os.environ.get("ODOO_REPO", "odoo/odoo")
    odoo_org, odoo_repo = odoo_full.split('/')
    server_dirname = "%s-%s" % (odoo_repo, odoo_version)
    server_path = os.path.join(travis_home, server_dirname)
    # Calculate addons_path
    addons_path_list = get_addons(travis_home)
    addons_path_list.insert(0, travis_build_dir)
    addons_path_list.append(server_path + "/addons")
    addons_path = ','.join(addons_path_list)

    if odoo_include:
        tested_addons_list = parse_list(odoo_include)
    else:
        tested_addons_list = get_modules(travis_build_dir)

    if odoo_exclude:
        exclude_list = parse_list(odoo_exclude)
        tested_addons_list = [
            x for x in tested_addons_list
            if x not in exclude_list]
    tested_addons = ','.join(tested_addons_list)

    print("Working in %s" % travis_build_dir)
    print("Using repo %s and addons path %s" % (odoo_full, addons_path))

    if not tested_addons:
        print("WARNING!\nNothing to test- exiting early.")
        return 0
    else:
        print("Modules to test: %s" % tested_addons)

    ## setup the base module without running the tests
    print("\nCreating test instance:")
    dbtemplate = "openerp_template"
    subprocess.check_call(["createdb", dbtemplate])

    preinstall_modules = 'mail' if odoo_unittest else tested_addons
    cmd_odoo = ["%s/openerp-server" % server_path,
                "-d", dbtemplate,
                "--log-level=warn",
                "--stop-after-init", \
                "--addons-path", addons_path,
                "--init", preinstall_modules,
                ] + install_options
    print(" ".join(cmd_odoo))
    subprocess.check_call(cmd_odoo)

    # Running tests
    database = "openerp_test"
    if odoo_unittest:
        to_test_list = tested_addons_list
        cmd_odoo_install = ["%s/openerp-server" % server_path,
                            "-d", database,
                            "--stop-after-init",
                            "--log-level=warn",
                            "--addons-path", addons_path,
                            ] + install_options + ["--init", None]

        cmd_odoo_test = ["coverage", "run",
                         "%s/openerp-server" % server_path,
                         "-d", database,
                         "--stop-after-init",
                         "--log-level", test_loglevel,
                         "--addons-path", addons_path,
                         ] + options + ["--update", None]

        commands = ((cmd_odoo_install, False),
                    (cmd_odoo_test, True),
                    )
    else:
        to_test_list = [tested_addons]
        cmd_odoo_test = ["coverage", "run",
                         "%s/openerp-server" % server_path,
                         "-d", database,
                         "--stop-after-init",
                         "--log-level", test_loglevel,
                         "--addons-path", addons_path,
                         ] + options + ["--init", None]
        commands = ((cmd_odoo_test, True),
                    )
    all_errors = []
    for to_test in to_test_list:
        print("\nTesting %s:" % to_test)
        subprocess.call(["createdb", "-T", dbtemplate, database])
        for command, check_loaded in commands:
            command[-1] = to_test
            print(' '.join(command))
            # Run test command; unbuffer keeps output colors
            command_call = ["unbuffer"] + command
            pipe = subprocess.Popen(command_call,
                                    stderr=subprocess.STDOUT,
                                    stdout=subprocess.PIPE)
            with open('stdout.log', 'w') as stdout:
                for line in pipe.stdout:
                    stdout.write(line)
                    print(line.strip())
            returncode = pipe.wait()
            # Find errors, except from failed mails
            errors = has_test_errors("stdout.log", database, odoo_version, check_loaded)
            if errors:
                all_errors.append(to_test)
                print(fail_msg, "Found %d lines with errors" % errors)
            if returncode != 0:
                all_errors.append(to_test)
                print(fail_msg, "Command exited with code %s" % returncode)
        subprocess.call(["dropdb", database])

    print('Module test summary')
    for to_test in to_test_list:
        if to_test in all_errors:
            print(fail_msg, to_test)
        else:
            print(success_msg, to_test)
    if all_errors:
        return 1
    # if we get here, all is OK
    return 0

if __name__ == '__main__':
    exit(main())
