#!/bin/bash

MODULES_TO_TEST=$TRAVIS_BUILD_DIR
PYLINT_CONFIG_DIR="$(dirname $0)/cfg"

# Fix pylint path. More info: https://www.mail-archive.com/code-quality@python.org/msg00294.html
export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
touch $MODULES_TO_TEST/__init__.py

# Set openerp in global path to fix "import" from addons
if [ "x${VERSION}" == "x" ] ; then
    VERSION="${1}"
    echo "WARNING: no env variable set for VERSION. Using '${1}'."
fi

: ${ODOO_REPO:="odoo/odoo"}  # default value, if not set
IFS="/" read -a REPO <<< "${ODOO_REPO}"
export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp

if [[ "${VERSION}" == 6.* ]] || [[ "${VERSION}" == 7.* ]] ; then
    # snake_case and CamelCase allow it for old version
    export CLASS_CASE='--class-rgx=([a-z_][a-z0-9_]{2,45})|([A-Z_][a-zA-Z0-9]{2,45})$'
fi

#run pylint command
pylint --rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg ${CLASS_CASE} ${MODULES_TO_TEST}
pylint_status=$?
if [[ "$pylint_status" == "0" ]]; then
  echo "Pylint OK"
  exit 0
else
  echo "Pylint ERRORS"
  exit 1
fi
