#!/usr/bin/env python

from __future__ import print_function

import os
import subprocess
import sys
from getaddons import get_addons
from getaddons import get_modules


def has_test_errors(fname, dbname, odoo_version):
    """
    Check a list of log lines for test errors.
    Extension point to detect false positives.
    """
    # Rules defining checks to perform
    ERRORS_IGNORE = [
        'Mail delivery failed',
        'failed sending mail',
        ]
    ERRORS_REPORT = [
        'CRITICAL %s' % dbname,
        'At least one test failed',
        # 'no access rules, consider adding one',
        ]
    # Only check ERROR lines before 7.0
    if odoo_version < '7.0':
        ERRORS_REPORT += ['ERROR %s' % dbname]

    print("-"*10)
    # Read log file removing ASCII color escapes:
    # http://serverfault.com/questions/71285
    cmd = 'sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" %s' % fname
    stdout = subprocess.check_output(cmd, shell=True).split('\n')
    errors = [
        line for line in stdout
        if any([err for err in ERRORS_REPORT if err in line])
        and not any([msg for msg in ERRORS_IGNORE if msg in line])
    ]
    if not any([l for l in stdout if 'Modules loaded.' in l]):
        errors.append("ERROR: Modules loaded message not found.")

    if errors:
        for e in errors:
            print(e)
        print("-"*10)
    return len(errors)


def parse_list(comma_sep_list):
    return [x.strip() for x in comma_sep_list.split(',')]


def main():
    travis_home = os.environ.get("HOME", "~/")
    travis_build_dir = os.environ.get("TRAVIS_BUILD_DIR", "../..")
    odoo_unittest = os.environ.get("UNIT_TEST")
    odoo_exclude = os.environ.get("EXCLUDE")
    odoo_include = os.environ.get("INCLUDE")
    odoo_version = os.environ.get("VERSION")
    if not odoo_version:
        # For backward compatibility, take version from parameter
        # if it's not globally set
        odoo_version = sys.argv[1]
        print("WARNING: no env variable set for VERSION. "
              "Using '%s'" % odoo_version)

    if odoo_version == "6.1":
        options = ""
        install_options = "--test-disable"
    else:
        options = "--test-enable"
        install_options = ""

    odoo_full = os.environ.get("ODOO_REPO", "odoo/odoo")
    odoo_org, odoo_repo = odoo_full.split('/')
    server_dirname = "%s-%s" % (odoo_repo, odoo_version)
    server_path = os.path.join(travis_home, server_dirname)
    # Calculate addons_path
    addons_path_list = get_addons(travis_home)
    addons_path_list.insert(0, travis_build_dir)
    addons_path_list.append(server_path + "/addons")
    addons_path = ','.join(addons_path_list)

    if odoo_include:
        tested_addons_list = parse_list(odoo_include)
    else:
        tested_addons_list = get_modules(travis_build_dir)

    if odoo_exclude:
        exclude_list = parse_list(odoo_exclude)
        tested_addons_list = [
            x for x in tested_addons_list
            if x not in exclude_list]
    tested_addons = ','.join(tested_addons_list)

    print("Working in %s" % travis_build_dir)
    print("Using repo %s and addons path %s" % (odoo_full, addons_path))

    if not tested_addons:
        print("WARNING!\nNothing to test- exiting early.")
        return 0
    else:
        print("Modules to test: %s" % tested_addons)

    ## setup the base module without running the tests
    print("\nCreating test instance:")
    dbtemplate = "openerp_template"
    subprocess.check_call("createdb %s" % dbtemplate, shell=True)

    preinstall_modules = 'mail' if odoo_unittest else tested_addons
    cmd_odoo = "%s/openerp-server %s -d %s --stop-after-init " \
               "--addons-path=%s --init=%s"
    cmd_options = (server_path, install_options, dbtemplate,
                   addons_path, preinstall_modules)
    subprocess.check_call(cmd_odoo % cmd_options, shell=True)

    # Running tests
    database = "openerp_test"
    if odoo_unittest:
        to_test_list = tested_addons_list
    else:
        to_test_list = [tested_addons]

    for to_test in to_test_list:
        print("\nTesting %s:" % to_test)
        subprocess.call(["dropdb", database])
        subprocess.call(["createdb", "-T", dbtemplate, database])

        cmd_odoo = "coverage run %s/openerp-server %s -d %s" \
                   " --stop-after-init --log-level=info" \
                   " --addons-path=%s --init=%s"
        cmd_options = (server_path, options, database,
                       addons_path, to_test)
        command = cmd_odoo % cmd_options
        print(command)
        # Run test command; unbuffer keeps output colors
        command_call = "unbuffer %s | tee stdout.log" % command
        subprocess.check_call(command_call, shell=True)
        # Find errors, except from failed mails
        errors = has_test_errors("stdout.log", database, odoo_version)
        if errors:
            print("Found %d lines with errors" % errors)
            return 1
    # if we get here, all is OK
    return 0

if __name__ == '__main__':
    exit(main())
