#!/usr/bin/env python
# coding: utf-8

from __future__ import print_function
from __future__ import unicode_literals
import os
import subprocess
import sys
from travis_helpers import success_msg, fail_msg


def main(test_list):
    """
    Loop through each test and run them, add display results at the end

    If the test has a .py extension, import as a list and call main function

    :param list test_list: list of lists containing commands to run
    :return: highest error code
    """
    args = sys.argv[1:]
    results = []
    for test in test_list:
        # keep backward compatibility with version as an argument
        print("======== Testing %s ========" % test[0])
        test_w_args = test + args
        test_file = test_w_args[0]
        if test_file.endswith(".py"):
            test_lib = test_file[:-3]
            try:
                res = __import__(test_lib).main(argv=test_w_args)
            except Exception as e:
                print(e)
                res = 1
        else:
            res = subprocess.call(test_w_args)
        results.append(res)

    print()
    print("+" + "="*39)
    print("|  Tests summary:")
    print("|" + "-"*39)
    for test, error in zip(test_list, results):
        outcome = fail_msg if error else success_msg
        print("| {0:<28}{1}".format(test[0], outcome))
    print("+" + "="*39)
    return max(results)


if __name__ == '__main__':
    lint_check_disabled = os.environ.get('LINT_CHECK') == '0'
    lint_check_enabled = os.environ.get('LINT_CHECK') == '1'
    tests_enabled = os.environ.get('TESTS') == '1'
    tests_unspecified = os.environ.get('TESTS') is None
    transifex_enabled = os.environ.get('TRANSIFEX') == '1'
    weblate_enabled = os.environ.get('WEBLATE') == '1'
    is_oca_project = os.environ.get('TRAVIS_REPO_SLUG', '').startswith('OCA/')
    is_oca_transifex_user = os.environ.get('TRANSIFEX_USER') == \
        'transbot@odoo-community.org'

    # TRAVIS_PULL_REQUEST contains the pull request number or 'false'
    is_pull_request = os.environ.get('TRAVIS_PULL_REQUEST') != 'false'
    # Avoid false red from forks using OCA transifex user
    is_valid_transifex = not is_pull_request and \
        (is_oca_project or not is_oca_transifex_user)

    # Test list. Each test is a list with command + arguments.
    tests = []

    if not lint_check_disabled:
        tests.append(['test_flake8'])
        tests.append(['test_pylint'])

    if tests_unspecified and not lint_check_enabled:
        tests.append(['test_server.py'])

    elif tests_enabled:
        tests.append(['test_server.py'])

    if transifex_enabled and is_valid_transifex:
        tests.append(['travis_transifex.py'])

    is_valid_weblate = (
        not is_pull_request and os.environ.get('UNIT_TEST') != '1' and
        ['test_server.py'] in tests)

    if weblate_enabled and is_valid_weblate:
        # Re-use database of TESTS=1 except if UNIT_TEST is enabled.
        tests.append(['travis_weblate.py'])

    if tests:
        exit(main(tests))
