#!/bin/bash

pip install -q QUnitSuite flake8 coveralls pylint Click > /dev/null 2>&1

# We can exit here and do nothing if this only a LINT check
if [ "${LINT_CHECK}" == "1" ] ; then
    exit 0
fi

if [ "x${VERSION}" == "x" ] ; then
    VERSION="${1}"
    echo "WARNING: no env variable set for VERSION. Using '${1}'."
fi

if [ -z $BOOTSTRAP_SCRIPT ] ; then
    BOOTSTRAP_SCRIPT=${TRAVIS_BUILD_DIR}/bootstrap.py
fi
echo "Executing bootstrap"
${BOOTSTRAP_SCRIPT}
echo "Launching bootstrap"
${TRAVIS_BUILD_DIR}/bin/buildout

export db_name=$(grep db_name ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
export db_user=$(grep db_user ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
export db_pass=$(grep db_password ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
psql -c "CREATE USER ${db_user} WITH PASSWORD '${db_pass}' CREATEDB;" -U postgres

# Expected directory structure:
#
#    HOME/
#     |___ build/
#     |___ maintainer-quality-tools/
#     ...

echo "Content of ${HOME}/:"
ls -l ${HOME}

# Expected directory structure:
#
#    TRAVIS_BUILD_DIR/
#     |___ bin/
#     |___ etc/
#     |___ parts/
#     |___ bootstrap.py
#     |___ buildout.cfg
#     ...

echo "Content of ${TRAVIS_BUILD_DIR}/:"
ls -l ${TRAVIS_BUILD_DIR}
