#!/usr/bin/env python

import os

from coverage.cmdline import main as coverage_main
from coveralls import cli as coveralls_cli
from codecov import main as codecov_main


if (os.environ.get('TESTS', '1') == '1' and
        os.environ.get('TEST_ENABLE', '1') == '1' and
        not os.environ.get('LINT_CHECK') == '1'):
    coverage_main(["report", "--show-missing"])
    try:
        coveralls_cli.main(argv=None)
    except:
        pass
    try:
        codecov_main(argv=None)
    except:
        pass
