#!/usr/bin/env python
import os
import subprocess
import sys

from getaddons import get_modules


root_dir = os.path.dirname(os.path.abspath(__file__))
status = 0

for addon in get_modules(os.path.abspath('.')):
    status += subprocess.call(['sphinx-apidoc',
                               '-f',
                               '-o',
                               'docs/source/addons/%s' % addon,
                               addon])
status += subprocess.call(['travis-sphinx', '-n', 'build'])

sys.exit(0 if status == 0 else 1)
