#!/bin/bash

set -v

flake8 . --config=../maintainer-quality-tools/travis/cfg/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=../maintainer-quality-tools/travis/cfg/travis_run_flake8.cfg
status2=$?
exit $((${status1} || ${status2}))
