#!/bin/bash

# For backward compatibility, take version from parameter if it's not globally set
if [ "x${VERSION}" == "x" ] ; then
    VERSION="${1}"
    echo "WARNING: no env variable set for VERSION. Using '${1}'."
fi

: ${ODOO_REPO:="odoo/odoo"}  # default value, if not set
IFS="/" read -a REPO <<< "${ODOO_REPO}"
ODOO_URL="https://github.com/${REPO[0]}/${REPO[1]}/archive/${VERSION}.tar.gz"

echo "Installing Odoo ${ODOO_URL}"
wget -O odoo.tar.gz ${ODOO_URL}
tar -xf odoo.tar.gz -C ../

sudo apt-get -q install expect-dev  # provides unbuffer utility
sudo apt-get -q install python-lxml  # because pip installation is slooow
sudo apt-get -q install antiword pdftotext

pip install -q QUnitSuite flake8 coveralls
pip install -q -r $(dirname ${BASH_SOURCE[0]})/requirements.txt


#webkit patched process
sudo apt-get -q install wkhtmltopdf
mkdir -p /tmp/webkit_patched
wget -O /tmp/webkit_patched/wkhtmltopdf.tar.bz2 https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2
bzip2 -dc /tmp/webkit_patched/wkhtmltopdf.tar.bz2 | tar -xvO >/tmp/webkit_patched/webkit-patched
sudo cp /tmp/webkit_patched/webkit-patched /usr/bin/wkhtmltopdf
