#!/bin/bash

LINE_LENGTH=120

flake8 . --max-line-length=${LINE_LENGTH} --filename=__init__.py --ignore=F401 --exclude=__unported__
status1=$?
flake8 . --max-line-length=${LINE_LENGTH} --exclude=__unported__,__init__.py
status2=$?
exit $((${status1} || ${status2}))
